apiVerrsion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/FY0323/argocd-test.git
    targetRevision: HEAD
    path: testpod

  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy: 
    automated:
      prune: false
      selfHeal: false