apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-fail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fail
  template:
    metadata:
      name: testpod-fail
      labels:
        app: fail
    spec:
      containers:
        - name: nginx-container
          image: 394881379225.dkr.ecr.ap-northeast-1.amazonaws.com/test/test03:ok02
          ports:
          - containerPort: 80