apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-fail-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fail02
  template:
    metadata:
      name: testpod-fail-02
      labels:
        app: fail02
    spec:
      containers:
        - name: nginx-container
          image: <set image>
          ports:
          - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1