apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-fail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fail
  template:
    metadata:
      name: testpod-fail
      labels:
        app: fail
    spec:
      containers:
        - name: nginx-container
          image: <set image>
          ports:
          - containerPort: 80
